### ISSUE TITLE
Unable to find info file if run from project root

### ISSUE THREAD

**Issue by kasperg** [xendk/bandaid#37]
After upgrading to 1.4 I am no longer able to run bandaid from the root of the project I want to work on. The problem is caused by the fact that [`getcwd()`](https://github.com/xendk/bandaid/blob/master/bandaid.drush.inc#L500) returns FALSE.

This leads to the following error message: 

`Could not find the info-file ".info" in`

Running the command from anothe directory or downgrading to 1.3 fixes the problem. I suspect that it is caused by #36.

**Comment by xendk** [comment]
Can't reproduce. Have a specific failure?

**Comment by kasperg** [comment]
I cannot either. Closed.
