### ISSUE TITLE
Diff contains packaging script info as changes

### ISSUE THREAD

**Issue by kasperg** [xendk/bandaid#38]
When given the project, wayf_dk_login version 7.x-1.0, and [a YML file of changes](https://raw.githubusercontent.com/reload/scribo-4/develop/profiles/scribo/modules/contrib/wayf_dk_login.yml?token=AAEg7sjnVuvjxt50M_9YevN1KonwhYlZks5Uz_AnwA%3D%3D) then the following actions will produce a patch with changes to `wayf_dk_login.info` which are not valid.

1. Remove the second patch from the YML file
2. Run bandaid-diff on the module
3. See that the diff contains changes to the info file

```diff
diff --git a/wayf_dk_login.info b/wayf_dk_login.info
index b6b4897..8ecd89c 100644
--- a/wayf_dk_login.info
+++ b/wayf_dk_login.info
@@ -6,3 +6,9 @@ dependencies[] = ctools
 dependencies[] = date
 dependencies[] = date_api
 configure = admin/config/people/wayf
+
+; Information added by  packaging script on 2013-11-18
+version = "7.x-1.0"
+core = "7.x"
+project = "wayf_dk_login"
+datestamp = "1384778606"
```

**Comment by xendk** [comment]
Can't reproduce. Still an issue?

**Comment by kasperg** [comment]
I can reproduce this using master.

**Comment by xendk** [comment]
I couldn't bandaid-apply the yml file either, without it complaining about local changes.

Turn out that the info file, for the 1.0 release at least, contains "; Information added by  packaging script on 2013-11-18", which is missing something.

Changed the regexp to take anything between "by " and " packaging".
